name: CI
# thanks for @mpariente for copying this workflow
# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  src-test:
    name: conda-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: museval
        auto-update-conda: true
        auto-activate-base: false
        python-version: ${{ matrix.python-version }}
    - name: Install Conda
      run: |
        conda install -c conda-forge ffmpeg libsndfile
    - name: Install dependencies
      run: |
        python -m pip install -e '.[tests]'
        python --version
        pip --version
        python -m pip list
    - name: Conda list
      run: conda list
    - name: Run tests
      run: |
        py.test tests -v
